services:

  db:
    image: mysql:8.0
    container_name: votoseguro-db

    env_file:
      - .env

    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}

    ports:
      - "3306:3306"

    volumes:
      - mysql_data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d

    networks:
      - votoseguro-network

  app:
    image: juan273/votoseguro:latest
    container_name: votoseguro-app

    env_file:
      - .env

    ports:
      - "8080:8080"

    depends_on:
      - db

    environment:
      DB_HOST: db
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}

    networks:
      - votoseguro-network

networks:
  votoseguro-network:
    driver: bridge

volumes:
  mysql_data: